controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# PdfSignableBundle: signature + AcroForm (single directory resource)
nowo_pdf_signable:
    resource: '@NowoPdfSignableBundle/Controller'
    type: attribute
    prefix: '/demo/pdf-signable'

# Web Profiler (dev)
_web_profiler:
    resource: routes/web_profiler.yaml
